name: PersonalFinanceDashboard

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8001:80"
    restart: unless-stopped
